<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_Paypal_inputCardNumber</name>
   <tag></tag>
   <elementGuidId>b8add62d-c603-4373-8e61-196a6fa20e47</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='credit-card-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#credit-card-number</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'credit-card-number' and @name = 'cardnumber' and @type = 'tel' and @ref_element = 'Object Repository/Page_Hobby_E2E_Testing/Hobby_iFramePaypal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>671fd9ec-5b38-42d8-83fc-b34337a84fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>credit-card-number</value>
      <webElementGuid>c9426d4d-2ed2-4eb4-b999-a5c714b30447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>40468d51-63a4-42d7-afa5-d8f290557593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>ffa287b8-d7f4-410d-90bb-59aee6719a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>6951118d-6f2b-49c1-9dd6-ba6357e1197e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardnumber</value>
      <webElementGuid>0832cbfe-9f4f-4d98-928d-2f6453d6a002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>99dc3f20-69ce-4ca0-ae71-132fd7dfb839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4cafa2a-f0e6-42cc-9382-ff472fbec90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1j2nbq5-inputStyles-rtlNumberOnlyStyles-FloatingLabelInput css-ezq4c9-FloatingLabelInputElement eticpaj2</value>
      <webElementGuid>5878794f-ba38-46e4-b08a-ae42b5ebafe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4032 0334 5177 6541</value>
      <webElementGuid>74dd4878-fdd6-4a16-af80-77665c0c88c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credit-card-number&quot;)</value>
      <webElementGuid>a1cb14b8-a653-4896-ab0d-1dccea421d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Hobby_E2E_Testing/Hobby_iFramePaypal</value>
      <webElementGuid>901c0fa7-7dfc-482f-ae8e-1d1f03673ee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='credit-card-number']</value>
      <webElementGuid>e65c4b45-4fd2-49c2-b3a2-57d0d5dffd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>ce2a1f44-5523-4441-913c-e3a3a2b7755d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9baf3224-a85c-4631-8436-9e289b608bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'credit-card-number' and @name = 'cardnumber' and @type = 'tel']</value>
      <webElementGuid>41cad232-7bf2-4e17-84ba-5c35c491d07a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
