<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_Paypal_input_Street1</name>
   <tag></tag>
   <elementGuidId>61ca929a-665d-46b6-bf5e-e1b0577773ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingAddress.line1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d41d6010-0028-4a83-a747-bb1044296813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23a2c823-b8a3-4606-906b-12f7c27f6ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingAddress.line1</value>
      <webElementGuid>1e10bc45-b946-48a9-93ce-600b08cd315d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>line1</value>
      <webElementGuid>18bd9b6b-55fc-44f1-9803-328216e39f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>billing street-address</value>
      <webElementGuid>a416eec6-b41f-4e14-9e47-e5907e1cf749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>be4d0167-c66e-4b31-ad75-4b9e5bab0524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-zkmphb-FloatingLabelInput css-ezq4c9-FloatingLabelInputElement eticpaj2</value>
      <webElementGuid>c1568f8c-d9cd-4d2e-a4bc-83ed2d78548b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAddress.line1&quot;)</value>
      <webElementGuid>c25bf8d4-1499-4f0b-967f-dbbf70127487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Hobby_E2E_Testing/Hobby_iFramePaypal</value>
      <webElementGuid>03faab6c-a84b-40cf-bdb1-72a0d1b22e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingAddress.line1']</value>
      <webElementGuid>4717f9b1-ac4a-4ba6-bb45-b91afeffa544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/div[4]/div[3]/div/div/div/input</value>
      <webElementGuid>fe409ebd-b6a3-4a3f-a2cc-8c45c6b66de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>a04b7ce3-0669-49cd-a0ee-d1069c5d4ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingAddress.line1' and @name = 'line1']</value>
      <webElementGuid>9c8a0772-94f0-43f1-8c30-7edf25ebfbde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
