<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_Paypal_inputCardNumber_expiry_date</name>
   <tag></tag>
   <elementGuidId>f13cf260-5b84-4b24-81db-a1325ceee6a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expiry-date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expiry-date</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'tel' and @id = 'expiry-date' and @name = 'expiry-date' and @ref_element = 'Object Repository/Page_Hobby_E2E_Testing/Hobby_iFramePaypal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf21d1d4-da6e-46fa-a311-8fa7d19cbc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4cc25808-8d9d-489a-b593-3bc7a4309e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry-date</value>
      <webElementGuid>ddef10de-49ce-4258-a354-029c722ace16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>79fd7c96-803c-43b5-959f-5cad122be1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry-date</value>
      <webElementGuid>d0c4ab69-891e-4950-b1ea-ea76de68652c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9de7c191-5aeb-4941-8fc5-c1c98faca831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-2aapkd-FloatingLabelInput css-ezq4c9-FloatingLabelInputElement eticpaj2</value>
      <webElementGuid>220bd1a7-b097-49c1-bc6d-52d908dde630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>0f16db52-afc6-4401-8c0e-5b38535c6301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12 / 28</value>
      <webElementGuid>fcf6f5f4-178a-4f97-a746-e031cc094699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry-date&quot;)</value>
      <webElementGuid>5c420148-e350-40f6-adf7-72032afc0e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Hobby_E2E_Testing/Hobby_iFramePaypal</value>
      <webElementGuid>d9867b43-6110-4c3f-840a-ac2885be52d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expiry-date']</value>
      <webElementGuid>1947da38-34d8-4986-85ce-4a8840ebd225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/div[3]/div/div/input</value>
      <webElementGuid>85f34586-f4fb-43c7-944f-b5d3aaf99139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>93df095a-17c4-4e33-98ff-c2d4469afd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'expiry-date' and @name = 'expiry-date']</value>
      <webElementGuid>7a17f607-8a1e-4476-8cbc-d289026c5f1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
