<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_inputPaybyPaypal</name>
   <tag></tag>
   <elementGuidId>79eb1fcb-a331-4d49-aefc-57bfe3eb10ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.css-1o7erft-MuiFormControlLabel-root > span.MuiRadio-root.MuiRadio-colorPrimary.MuiButtonBase-root.MuiRadio-root.MuiRadio-colorPrimary.PrivateSwitchBase-root.css-fid63b-MuiButtonBase-root-MuiRadio-root > input[name=&quot;mui-3&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='mui-3'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e464088-07ec-4f54-b66b-0f6d96791cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input css-1m9pwf3</value>
      <webElementGuid>1aab78e2-6d13-4373-b30e-6d5cf92ef954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>68f4b426-44af-4144-a49d-aca77eec07cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>paypal</value>
      <webElementGuid>2af03e4f-c2b6-41ac-8386-10181e384a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mui-3</value>
      <webElementGuid>9187ab23-0d74-4db5-9518-672c835760f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;layout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;checkout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-1vt60ei-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-3 css-iv7vbz-MuiGrid-root&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-outlined MuiPaper-rounded MuiCard-root payment-wrapper css-1jrv6xy-MuiPaper-root-MuiCard-root&quot;]/div[@class=&quot;MuiBox-root css-q5fqw0&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiFormGroup-root css-dmmspl-MuiFormGroup-root&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-1o7erft-MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiRadio-root MuiRadio-colorPrimary MuiButtonBase-root MuiRadio-root MuiRadio-colorPrimary PrivateSwitchBase-root css-fid63b-MuiButtonBase-root-MuiRadio-root&quot;]/input[@class=&quot;PrivateSwitchBase-input css-1m9pwf3&quot;]</value>
      <webElementGuid>5c613aef-5ea0-4f1b-86b7-bcf8e042a0ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='mui-3'])[2]</value>
      <webElementGuid>4ecba1c3-2034-43f2-af9d-d57ecf397a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div/div[2]/div/div/div/div/label[2]/span/input</value>
      <webElementGuid>66626dcf-3594-4ce0-a3ad-ab6fe3d5c3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span/input</value>
      <webElementGuid>a8f5ad8c-a4e4-43fa-9c9c-0c5cd634d1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'mui-3']</value>
      <webElementGuid>0becb13e-e1ee-43fe-9e5a-828b7cf8876c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
