<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_buttontheNumberofProduct</name>
   <tag></tag>
   <elementGuidId>5bf0cf4b-5022-4b30-a327-25cce9f6c31a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cell-center.quantity.MuiBox-root.css-0 > button:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[2]/div/div/div/div/div[4]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08a6259d-b93f-4a2c-a6e5-722952e7a47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;layout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;cart-page-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;content-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;cart-item-wrapper MuiBox-root css-0&quot;]/div[1]/div[@class=&quot;cart-item css-vyxe4v-MuiStack-root&quot;]/div[@class=&quot;cell-center quantity MuiBox-root css-0&quot;]/button[2]</value>
      <webElementGuid>f5d224b2-b996-46f5-a6e6-11623bf79d3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div/div/div/div/div[4]/button[2]</value>
      <webElementGuid>6944d2b9-8201-414c-9bf0-941598b8bf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow us'])[1]/preceding::button[2]</value>
      <webElementGuid>8966aef0-a6a3-4879-bca2-79185c2f5cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>a991e65c-dd85-42f0-901c-25fcd3dac2af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
