<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_Login_inputPassword</name>
   <tag></tag>
   <elementGuidId>93fad25f-e0b0-4ba0-beab-291fb1b20bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth-login-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#auth-login-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef415d35-89e5-4884-bdbb-47074b76ea0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e5707cf0-0aa4-49b3-bbfe-5c6b8471c382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71983721-7b21-45aa-a233-c260fa1d31d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a489b73f-d903-4a07-8872-250c502de212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-login-password</value>
      <webElementGuid>4d9dfc3f-aeba-4591-800c-6f54afb07668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>44c596c2-f944-4e14-addc-750bb3f8985c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-17znf35-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>92d33bcd-4e62-4b3c-9734-b89fc4a363af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-login-password&quot;)</value>
      <webElementGuid>245df098-87df-4070-ad3f-102f4cc7aece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth-login-password']</value>
      <webElementGuid>a237bff3-67fb-4b98-bb39-bafc2c311605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>08460f92-db43-4d0c-96e0-a7ff564313de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>bb9c3bbd-51c7-41b3-ba04-c73e631ca1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'auth-login-password' and @name = 'password']</value>
      <webElementGuid>c6fb91ca-3ac6-4600-9ebe-2ffa899ec6dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
