<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_Login_LoginSuccessfully</name>
   <tag></tag>
   <elementGuidId>83a3db65-31b9-48b6-8a29-87be3fc0244b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[2]/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>fd43360f-517b-4775-8ff3-c475267b94cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BỘ SƯU TẬP OSAKA</value>
      <webElementGuid>cb5b54f8-9dd4-4edd-843a-ffedcf0903d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;layout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;home-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;banner&quot;]/div[@class=&quot;text-box-content&quot;]/h2[1]</value>
      <webElementGuid>ed9cf664-262c-4e4f-84c7-9172a3b904bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div/div/h2</value>
      <webElementGuid>b1d5a4fc-e324-4fb2-adec-3e3a1b66e77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Góc cảm ứng'])[1]/following::h2[1]</value>
      <webElementGuid>35188402-d843-40fd-b3ea-687190df6285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showroom ảo'])[1]/following::h2[1]</value>
      <webElementGuid>3d506c45-58bd-42a1-9c73-94bfd7d7aa12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KHÁM PHÁ NGAY'])[1]/preceding::h2[1]</value>
      <webElementGuid>523d6eae-2d88-41d0-8b23-06e1165e00d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm hot'])[1]/preceding::h2[1]</value>
      <webElementGuid>ab59a94a-ca77-417f-b24f-ca3ac5543368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BỘ SƯU TẬP OSAKA']/parent::*</value>
      <webElementGuid>7dec1746-0fbf-4038-bd65-abde18875fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>af19ceeb-8211-456b-9518-9a47aac8f710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'BỘ SƯU TẬP OSAKA' or . = 'BỘ SƯU TẬP OSAKA')]</value>
      <webElementGuid>c10162d2-7354-4203-a12a-75d3dd1218bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
