<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_spanCart</name>
   <tag></tag>
   <elementGuidId>0f060025-9aee-45aa-b6c1-84bcc2ca3fc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div[2]/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > span.is-desktop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9baae06-d949-499a-90ea-7332e637c27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-desktop</value>
      <webElementGuid>231feed1-01ff-4783-9d22-53231a4ca7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giỏ hàng</value>
      <webElementGuid>70cf353a-dafa-41eb-a80d-d00da1c3f090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;layout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;top-box&quot;]/div[@class=&quot;right-list&quot;]/div[@class=&quot;left-list-item&quot;]/span[1]/span[@class=&quot;is-desktop&quot;]</value>
      <webElementGuid>faf5a4f4-3154-413c-8432-a40a99082a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div[2]/div/span/span</value>
      <webElementGuid>712bb05c-dfd3-4c1a-9423-5f1d519bc807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giảm giá đặc biệt'])[1]/following::span[2]</value>
      <webElementGuid>76b7ad72-dde1-41bb-957a-cb11169785f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khuyến mãi'])[1]/following::span[2]</value>
      <webElementGuid>e188d144-5a50-4c63-905f-4ebbb4a35fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/preceding::span[1]</value>
      <webElementGuid>b34469ae-8c37-4876-9885-a100741e0e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm'])[1]/preceding::span[3]</value>
      <webElementGuid>8c48e439-bde0-4dec-8f09-6c1ad6da5f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Giỏ hàng']/parent::*</value>
      <webElementGuid>0886dda7-aeef-4c07-9640-a525c49290e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>d76132da-fd91-4cca-ae6e-49095d19d095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Giỏ hàng' or . = 'Giỏ hàng')]</value>
      <webElementGuid>1275531c-c78d-4bd0-94c5-2548220d4057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
