<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>284f3ed3-2ba4-4aab-8466-4b93023243e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnNext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnNext']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54b36974-e208-4b6d-adad-e3fabe8fb231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button actionContinue scTrack:unifiedlogin-login-click-next</value>
      <webElementGuid>f49b7e1d-c2cd-496f-add7-c8aff059d0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e11b4907-1161-452a-a8d0-5a50b8eb9e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNext</value>
      <webElementGuid>0e77a2f5-ce78-401d-881c-e04f4d9f759b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnNext</value>
      <webElementGuid>a1271164-123c-4b8e-95f9-d8a4a019e779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>e5893c28-196d-4a34-9f5d-0a90f59d54d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9717b012-1c9a-419a-bbb4-4b7cad8c2fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>a439cfef-766b-4b71-a7b6-0f310bc2ee7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNext&quot;)</value>
      <webElementGuid>bf34f1fb-7238-4f5a-8d27-8c85efdbfc0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnNext']</value>
      <webElementGuid>eab2945f-389d-447b-b450-17ff9a819fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='splitEmail']/div[2]/button</value>
      <webElementGuid>9f005e0d-fcc4-4763-931e-2dafbbcc03bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio Button'])[1]/following::button[1]</value>
      <webElementGuid>b9d6c80d-a1ce-4387-a7f4-e3dd875bcdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reload Image'])[1]/following::button[1]</value>
      <webElementGuid>73c2cf14-d2e2-458d-86da-67de8d88befc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::button[1]</value>
      <webElementGuid>499de2e8-c995-40d0-a8b4-6d869f08a1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show password'])[1]/preceding::button[1]</value>
      <webElementGuid>0a7f8fa4-abc4-4faa-b1fa-e70f0f0c0469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>d285c1ea-c340-47ee-91e6-0bdbb55b2837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>eb623c64-7975-4637-bbf6-523b4b5a59e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnNext' and @name = 'btnNext' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>076c1fae-7b51-4948-9df8-62330d9a9342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
