<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gc cm ng_searchQuery</name>
   <tag></tag>
   <elementGuidId>0f913dcc-63ed-4684-9f3f-318d0decd9c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchQuery']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchQuery&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e006fd50-6d49-42e1-a732-8962a9e606cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>015c8dfd-5c21-4678-b2c5-f31cc28da86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm</value>
      <webElementGuid>fe5d7fc4-d4a8-461e-8df5-a13707e577b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchQuery</value>
      <webElementGuid>93ac0da2-7cd9-45e4-9e65-ce44321b4717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;layout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;bottom-box&quot;]/div[@class=&quot;right-list&quot;]/form[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;search&quot;]/input[1]</value>
      <webElementGuid>c9e401ed-36ce-45df-a64a-6e7d4440da82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchQuery']</value>
      <webElementGuid>8c06cf4c-6645-4625-a92b-445db640657d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[2]/div[2]/form/div/input</value>
      <webElementGuid>24c57ca7-9734-4fcd-8331-62cd9416b786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>06a4dfa8-edf1-4a83-bff3-6ddaae184f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Tìm sản phẩm' and @name = 'searchQuery']</value>
      <webElementGuid>5da688a0-e499-4b5a-8d46-7a325a929beb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
