<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_Searching_DetailedDescription</name>
   <tag></tag>
   <elementGuidId>0c7bfb45-e09f-494d-841f-d5274dcb1e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>c70b2b4e-d25e-4ecc-a85f-704cd3f488d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>4cdcc474-a2df-4bc9-ba52-4ef1f8d3b9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mô tả chi tiết</value>
      <webElementGuid>b07172cd-f221-4a7c-b5de-4abe0b0e9f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;layout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;product-description&quot;]/div[@class=&quot;content-wrapper&quot;]/h3[@class=&quot;title&quot;]</value>
      <webElementGuid>773a0fc6-5839-4b90-9c41-c9fd5874349a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/h3</value>
      <webElementGuid>dc9f1ec5-d244-48bd-9381-1f9cf3a7f932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trải nghiệm'])[1]/following::h3[1]</value>
      <webElementGuid>f0eb5008-f15c-440a-a2bd-bf50ada3c693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm liên quan'])[1]/preceding::h3[1]</value>
      <webElementGuid>a432fad0-8398-4965-9100-b6090793fe14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sofa Coastal 1 chỗ'])[2]/preceding::h3[2]</value>
      <webElementGuid>239b8c44-3788-4587-a50c-60e05e715449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mô tả chi tiết']/parent::*</value>
      <webElementGuid>fc6dbc9d-5b79-4d52-a766-fa544d15bea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>982ca7d0-7caa-456d-ac9a-047e9a74e925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Mô tả chi tiết' or . = 'Mô tả chi tiết')]</value>
      <webElementGuid>e434a43b-ff43-45fe-b044-9ba028f2bd99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
