<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_Searching_buttonSearch</name>
   <tag></tag>
   <elementGuidId>95527b1a-9de4-4d4f-955d-15e15ea5d1a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div[2]/div[2]/form/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.search-btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'search-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e0d6bf6-eedf-49c2-bc81-cdec1de3548b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-btn</value>
      <webElementGuid>725d00e1-b5b1-4002-83aa-8d25b9c136fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;layout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;bottom-box&quot;]/div[@class=&quot;right-list&quot;]/form[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;search&quot;]/button[@class=&quot;search-btn&quot;]</value>
      <webElementGuid>07c72b89-a619-4444-bf3c-78d4c03716b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[2]/div[2]/form/div/button</value>
      <webElementGuid>40a92bde-6b1a-4031-9489-29487ba6ec1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Góc cảm ứng'])[1]/following::button[1]</value>
      <webElementGuid>60ff3ff2-1fd3-4101-862c-9fce1e630392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showroom ảo'])[1]/following::button[1]</value>
      <webElementGuid>5e56123f-5680-4ac2-9b34-95986873216f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BỘ SƯU TẬP OSAKA'])[1]/preceding::button[2]</value>
      <webElementGuid>fda00031-fa21-4e61-a840-dc2921f64bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KHÁM PHÁ NGAY'])[1]/preceding::button[2]</value>
      <webElementGuid>25ae74f2-9e08-4abc-88af-ef43137fbfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2e3d6b4e-6b26-4e6a-bd70-49fde8048563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
