<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobby_Searching_inputProduct</name>
   <tag></tag>
   <elementGuidId>f195b583-2ef3-4847-bcda-7d358945acc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchQuery']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchQuery&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a279d9a-99af-4058-8687-c77871f1fdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>52bac475-b98b-461d-a29d-e1adf1e72dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm</value>
      <webElementGuid>365cd2f8-f008-4825-9b4c-2fae880452cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchQuery</value>
      <webElementGuid>497237ba-7e83-4992-91cb-3bbfe0ccd27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;layout-wrapper MuiBox-root css-0&quot;]/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;bottom-box&quot;]/div[@class=&quot;right-list&quot;]/form[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;search&quot;]/input[1]</value>
      <webElementGuid>6c87965d-22fd-4e3c-8e43-520b4ea4b872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchQuery']</value>
      <webElementGuid>479ed30a-fa72-477e-a57f-fd659f2f0399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[2]/div[2]/form/div/input</value>
      <webElementGuid>ae9f487f-29c8-4288-ab34-a5c2bee2a95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>641e6342-84b6-4b4e-a62a-2fb2f0a7a865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Tìm sản phẩm' and @name = 'searchQuery']</value>
      <webElementGuid>1cc6a998-42ee-40ff-aad3-5dd11936dcb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
